#!/bin/bash

# Extension for easy note finding
M2NOTE_EXT='.m2'

usage() {
  echo 'usage goes here!'
}

# Just prints text with a new line before
# pp stands for padded print
pp() {
  echo ''
  echo $1
}

# check if the notes path exists
check_path() {
  # If M2NOTE_PATH variable is NOT set
  if [ -z $M2NOTE_PATH ]; then
    pp 'Please set M2NOTE_PATH, such as: '
    pp "    export M2NOTE_PATH=$HOME/.m2note"
    exit 1
  fi
}

# Create the notes directory
create_notes_dir() {
  pp 'Creating notes directory'
  mkdir $M2NOTE_PATH
  # if the last command was NOT successful
  if [ $? -ne 0 ]; then
    pp 'Could note create notes directory'
    exit 1
  fi
}

# Check if the note directory exists, and call create_notes_dir if not
check_dir() {
  # If the directory of $M2NOTE_PATH does NOT exist (remove ! to return true if set)
  if [ ! -d "$M2NOTE_PATH" ]; then
    create_notes_dir
  fi
}

# Deletes notes from passed parameters
delete_notes() {
  local file
  local ERROR
  for file in "$@"; do
      echo "Deleting $file"
      ERROR=$(rm $M2NOTE_PATH/$file$M2NOTE_EXT 2>&1 >/dev/null)

      if [ $? -ne 0 ]; then
        pp 'Could not delete note due to:'
        echo $ERROR
      else
        pp "Successfully deleted: $file"
      fi
  done
}

# Creates a new from passed params
quick_note() {

  # Check if we have more than 0 arguments passed
  if [ "$#" -gt 0 ]; then
    local file=$1
    shift

    if [ "$#" -gt 0 ]; then
      echo $@ >> $M2NOTE_PATH/$file$M2NOTE_EXT
    else
      touch $M2NOTE_PATH/$file$M2NOTE_EXT
    fi

    echo "Updated note: $file"
  else
    pp 'You must provide a note name'
    exit 1
  fi
}

# Prints out note/notes. Expects params
show_note() {
  if [ "$#" -gt 0 ]; then
    echo 'show note'
  else
    pp 'Please provide notes to print'
  fi
}

list() {
  pp 'Current notes are:'
  echo '===================='

  # Find all entries in M2NOTE_PATH that are a file type and have the M2NOTE_EXT extension
  local entries=$(find $M2NOTE_PATH -type f -name "*$M2NOTE_EXT")
  for entry in $entries
  do
    # Returns the filename of $entry and stripping off $M2NOTE_EXT
    basename $entry $M2NOTE_EXT
  done
}

main() {
  check_path
  check_dir
  # Keep opt local
  local opt
  local OPT_FLAG_D=0
  # syntax is getopts [arguments] [variable to check]
  while getopts :l:d:q opt
  do
    case $opt in
      l)
        list
        exit 0
        ;;
      d)
        OPT_FLAG_D=1
        shift
        ;;
      q)
        shift
        quick_note $@
        exit 0
        ;;
      \?)
        usage
        shift
        ;;
    esac
  done

  if [ "$#" -eq 0 ]; then
    list
    exit 0
  fi

  if [ "$OPT_FLAG_D" -eq 1 ]; then
    delete_notes $@
    exit 0
  fi

  if [ "$#" -eq 1 ]; then
    "${EDITOR:-vi}" $M2NOTE_PATH/$1$M2NOTE_EXT
    exit 0
  fi
}

# Pass all arguments to main
main "$@"
